modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="apothic_cataclysm"
version="${file.jarVersion}" #mandatory
displayName="Apothic Cataclysm" #mandatory
logoFile="logo.png" #optional
credits="LightLand team" #optional
authors="lcy0x1" #optional
description='''
This mod adds Cataclysm weapons to Aptheosis bosses after you defeat respective Cataclysm bosses
'''
[[dependencies.apothic_cataclysm]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.apothic_cataclysm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.apothic_cataclysm]]
    modId="apotheosis"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.apothic_cataclysm]]
    modId="cataclysm"
    mandatory=true
    versionRange="[0,)"
    side="BOTH"